variables:
  IMAGE: ubuntu:with-rust
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage build
##############################################################################
build:
  stage: build
  script:
    - cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
    - cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit --release
  image: ${IMAGE}
  cache:
    paths:
      - target/x86_64-unknown-hermit/debug/rusty_demo
    key: build
  artifacts:
    paths:
      - target/x86_64-unknown-hermit/debug/rusty_demo
  tags:
    - docker

# Stage: test

##############################################################################
#test:tarpaulin:
#  stage: test
#  script:
#    - rm -rf tests loader
#    - cargo tarpaulin -v --exclude-files src/arch/aarch64
#  image: ${IMAGE}
#  tags:
#    - docker

#test:cargo:
#  stage: test
#  script: 
#    - cargo test --target x86_64-unknown-linux-gnu
#  image: ${IMAGE}
#  tags:
#    - docker

test:qemu:
   stage: test
   script:
     - cd loader
     - make
     - qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio -kernel target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd ../target/x86_64-unknown-hermit/debug/rusty_demo -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr
	 - qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio -kernel target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd ../target/x86_64-unknown-hermit/release/rusty_demo -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr
