[workspace]
resolver = "2"
members = [
    "benches/alloc",
    "benches/micro",
    "benches/netbench",
    "examples/demo",
    "examples/fuse_test",
    "examples/hello_world",
    "examples/httpd",
    "examples/miotcp",
    "examples/mioudp",
    "examples/polling",
    "examples/rftrace-example",
    "examples/testtcp",
    "examples/testudp",
    "examples/tls",
    "examples/tokio",
    "examples/webserver",
    "examples/dns",
    "examples/mutex",
    "examples/fibonacci",
    "examples/wasmtime",
    "hermit",
    "hermit-abi",
]

[patch.crates-io]
hyper-util = { git = "https://github.com/hermit-os/hyper-util.git", branch = "hermit" }
mio = { git = "https://github.com/hermit-os/mio.git", branch = "v0.8.x" }
rustls-rustcrypto = { git = "https://github.com/RustCrypto/rustls-rustcrypto", rev = "e6d5ed9652228ff09e56fee2534b6f60877fb7b8" }
socket2 = { git = "https://github.com/hermit-os/socket2.git", branch = "hermit" }
tokio = { git = "https://github.com/hermit-os/tokio.git", branch = "hermit" }
tokio-rustls = { git = "https://github.com/hermit-os/tokio-rustls.git", branch = "v/0.26.0" }
