[workspace]
resolver = "2"
members = [
    "hermit-abi",
    "hermit-sys",
    "benches/alloc",
    "benches/netbench",
    "benches/micro",
    "examples/tokio",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
]
exclude = ["target", "libhermit-rs"]
