[package]
name = "hermit-abi"
version = "0.1.1"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
hermit-abi is small interface to call functions from the unikernel RustyHermit.
It is used to build the target `x86_64-unknown-hermit`.
"""
repository = "https://github.com/hermitcore/hermit-abi"
keywords = ["unikernel", "libos"]
categories = ["os"]
exclude = ["/.travis.yml", "/.gitlab-ci.yml", ".gitignore", ".rustfmt.toml"]

[dependencies]
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "0.1.0", optional = true }
libc = { version = "0.2.51", default-features = false, features = ['rustc-dep-of-std'] }

[features]
docs = []
rustc-dep-of-std = ["core", "compiler_builtins/rustc-dep-of-std"]

[package.metadata.docs.rs]
features = ["docs"]
