[workspace]
resolver = "2"
members = [
    "benches/alloc",
    "benches/micro",
    "benches/netbench",
    "examples/axum",
    "examples/demo",
    "examples/fuse_test",
    "examples/hello_world",
    "examples/httpd",
    "examples/miotcp",
    "examples/mioudp",
    "examples/polling",
    "examples/rftrace-example",
    "examples/testtcp",
    "examples/testudp",
    "examples/tls",
    "examples/thread_test",
    "examples/tokio",
    "examples/webserver",
    "examples/dns",
    "examples/mutex",
    "examples/wasm-test",
    "examples/hermit-wasm",
    "examples/vsock",
    "hermit",
    "hermit-abi", 
    "benches/startup",
]

[patch.crates-io]
hyper-util = { git = "https://github.com/hermit-os/hyper-util.git", branch = "v/0.1.11" }
socket2 = { git = "https://github.com/hermit-os/socket2.git", branch = "v0.5.x" }
tokio = { git = "https://github.com/hermit-os/tokio.git", branch = "v/tokio-1.45.0" }
