[toolchain]
# Manually sync this with Dockerfile!
channel = "nightly-2022-09-10"
components = [
    "clippy",
    "llvm-tools-preview",
    "rustfmt",
    "rust-src",
]
targets = [ "x86_64-unknown-hermit" ]
