[package]
name = "hermit-sys"
version = "0.1.25"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
description = "FFI bindings to HermitCore"
repository = "https://github.com/hermitcore/rusty-hermit"
readme = "README.md"
keywords = ["unikernel", "libos"]
categories = ["os"]
links = "hermit"
build = "build.rs"
edition = "2021"
documentation = "https://hermitcore.github.io/rusty-hermit/hermit_sys"

[features]
default = [
    "acpi",
    "pci",
    "smp",
    "fsgsbase",
]

aarch64-qemu-stdout = []
acpi = []
dhcpv4 = ["smoltcp/proto-dhcpv4"]
fsgsbase = []

# Build the kernel with function instrument code for mcount-based tracing
instrument = ["rftrace"]

pci = []
smp = []
tcp = [
    "async-task",
    "concurrent-queue",
    "futures-lite",
    "lazy_static",
    "smoltcp",
]
trace = []
vga = []

# Internal feature for building the kernel from local sources
with_submodule = []

[dependencies]
log = { version = "0.4", default-features = false }
libm = { version = "0.2", default-features = false }

async-task = { version = "4.0", optional = true }
concurrent-queue = { version = "1.2", optional = true }
futures-lite = { version = "1.11", optional = true }
lazy_static = { version = "1.4", optional = true }

[dependencies.smoltcp]
version = "0.7"
optional = true
default-features = false
features = ["std", "ethernet", "socket-udp", "socket-tcp", "proto-ipv4", "proto-ipv6", "async"]
# to increase the output the features log and verbose should be enabled
#features = ["log", "verbose", "std", "ethernet", "socket-udp", "socket-tcp", "proto-ipv4", "proto-ipv6", "async"]

[dependencies.rftrace]
version = "0.1"
optional = true
features = ["autokernel", "buildcore", "interruptsafe"]

[target.'cfg(target_arch = "x86_64")'.dependencies.x86]
version = "0.46"
default-features = false

[target.'cfg(target_arch = "aarch64")'.dependencies.aarch64]
version = "0.0.7"
default-features = false

