[package]
name = "hermit-sys"
version = "0.1.19"
authors = ["Stefan Lankes"]
license = "MIT/Apache-2.0"
description = "FFI bindings to HermitCore"
repository = "https://github.com/hermitcore/rusty-hermit"
readme = "README.md"
keywords = ["unikernel", "libos"]
categories = ["os"]
links = "hermit"
build = "build.rs"
edition = "2018"
documentation = "https://hermitcore.github.io/rusty-hermit/hermit_sys"

[features]
default = ["pci", "acpi", "smp", "fsgsbase"]
# controlls whether RustyHermit is build with -Z instrument-mcount
instrument = ["rftrace"]
trace = []
fsgsbase = []
pci = []
acpi = []
# only for internal usage, please don't use it
with_submodule = []
smp = []

[build-dependencies]
walkdir = "2"
target_build_utils = "0.3"
llvm-tools = { version = "0.1" }

[dependencies]
log = { version = "0.4", default-features = false }
lazy_static = "1.4.0"
libm = { version = "0.2.1", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies.x86]
version = "0.*"
default-features = false

[target.'cfg(target_arch = "aarch64")'.dependencies.aarch64]
version = "0.*"
default-features = false

[dependencies.smoltcp]
version = "0.6.0"
optional = true
default-features = false
features = ["std", "ethernet", "socket-udp", "socket-tcp", "proto-ipv4", "proto-ipv6"]
# to increase the output the features log and verbose should be enabled
#features = ["log", "verbose", "std", "ethernet", "socket-udp", "socket-tcp", "proto-ipv4", "proto-ipv6"]

[dependencies.rftrace]
version = "0.1.0"
optional = true
features = ["autokernel", "buildcore", "interruptsafe"]

